# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork
  SamLocal-Fork:
    cmd_settings:
      unlock:
        - 0xBE0eB53F46cd790Cd13851d5EFf43D12404d33E8
        - 0xC3D6880fD95E06C816cB030fAc45b3ffe3651Cb0
        - 0xf2d373481e1da4a8ca4734b28f5a642d55fda7d3
        - 0x767Ecb395def19Ab8d1b2FCc89B3DDfBeD28fD6b
        - 0x3f5CE5FBFe3E9af3971dD833D26bA9b5C936f0bE
      fork: 'http://127.0.0.1:9999'

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - iearn-finance/yearn-vaults@0.3.0
  - OpenZeppelin/openzeppelin-contracts@3.1.0

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@yearnvaults=iearn-finance/yearn-vaults@0.3.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"

reports:
  exclude_contracts:
    - SafeMath
